import type { Metadata } from "next";
import "./globals.css";
import MenuComponent from "@/components/menu/menuComponent";
import {ThemeProvider} from "next-themes";

export const metadata: Metadata = {
  title: "Movies Universe V2 NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"body"}>


      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <MenuComponent/>
        {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
