import type { Metadata } from "next";
import "./globals.css";
import MenuComponent from "@/components/menu/MenuComponent";
import {ThemeProvider} from "next-themes";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Movies Universe by NextJS",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={"body"}>


      <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <MenuComponent/>
        {children}
          <Footer/>
      </ThemeProvider>
      </body>
    </html>
  );
}
