import type { Metadata } from "next";
import "./globals.css";
import MenuComponent from "@/components/menu/menuComponent";


export const metadata: Metadata = {
  title: "Movies Universe V2 NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <MenuComponent/>
        {children}
      </body>
    </html>
  );
}
